### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by jeffhammond** [intel/parallelstl#2]
TBB has Homebrew support: [tbb.tb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tbb.rb).

Because PSTL is just headers, the formula should be extremely simple, as it just needs to grab the headers and register TBB as a dependency.

I'll try to work on this but it would be great if someone else did it first.

**Comment by henryiii** [comment]
(This can be closed, the formula was merged; you can now `brew install parallelstl`.)

**Comment by tbbdev** [comment]
Hi @henryiii, @ilovezfs,

Thank you! We really appreciate your efforts!

What do you think about an auto detection of new Parallel STL releases?

It can be done using GitHub API:
you can get "tag_name" from https://api.github.com/repos/intel/parallelstl/releases/latest and then use it in `https://github.com/intel/parallelstl/archive/<tag_name>.tar.gz`

The only question is how to retrieve sha256 of the archive…

**Comment by henryiii** [comment]
I think that's pretty close to what `brew bump-formula-pr` does, see Homebrew/homebrew-core#25695 for example.

**Comment by henryiii** [comment]
And I always subscribe via RSS to https://github.com/USER/REPO/releases.atom, such as https://github.com/intel/parallelstl/releases.atom in this case.

**Comment by tbbdev** [comment]
Thanks, henryiii.
So, we're closing the issue
