### ISSUE TITLE
Refactoring broke glue_algorithm_defs.h

### ISSUE THREAD

**Issue by ahmadsarvmeily** [intel/parallelstl#23]
pstl namespace usages should have also been renamed to __pstl in glue_algorithm_defs.h, commit b962d08

I got errors trying to build the current master branch, and these were fixed by doing this renaming.

**Comment by tbbdev** [comment]
Hello, ahmadsarvmeily!
Thank you for the issue.  It has been fixed. See commit  01bbef9b845b2aa855bb5e95f850cddeb62901df
