### ISSUE TITLE
FindTBB.cmake should check for TBB_FOUND

### ISSUE THREAD

**Issue by hansgans** [intel/parallelstl#26]
I saw that you have recently added `FindTBB.cmake` which is used by `CMakeLists.txt`. I think you should put all contents from `FindTBB.cmake` in a 
```
if(NOT TBB_FOUND)
...
endif()
```
At least that is what is done in most other `FindXYZ.cmake` files.
In my case `find_library(TBB)` is called somewhere else und produces errors when `FindTBB.cmake` tries to add targets twice.

**Comment by tbbdev** [comment]
@hansgans, thank you for the issue! We will address it in future releases.

**Comment by tbbdev** [comment]
Fixed in the [new](https://github.com/intel/parallelstl/blob/20190429/CHANGES) release.
