### ISSUE TITLE
std::transform fails to apply to all elements

### ISSUE THREAD

**Issue by mfdeakin** [intel/parallelstl#27]
The following minimal reproducer fails randomly when using the `par` and `par_unseq` execution policies, but passes when using the `seq` or just the default transform.

```
#include <algorithm>
#include <execution>

#include <assert.h>

int main(int argc, char **argv) {
  constexpr int size = 1024;
  std::vector<double> v(size);
  for (int i = 0; i < size; i++) {
    const double value = static_cast<double>(i);
    v[i] = value * value + 5.0 * value;
  }

  constexpr double min_v = 1000000.0;
  std::vector<bool> ge_v(size);
  for (int pass = 0; pass < 10; pass++) {
    std::transform(std::execution::par, v.begin(), v.end(), ge_v.begin(),
                   [](const double v) { return v >= min_v; });
    for (int i = 0; i < v.size(); i++) {
      assert((v[i] >= min_v) == ge_v[i]);
    }
  }
  return 0;
}
```

This is with the version of the parallel included with GCC 9.1. My GCC version is `9.1.1 20190503 (Red Hat 9.1.1-1)`. My version of `tbb` is `tbb-devel-2019.5-1.fc30.x86_64`, which I believe is just the latest release, 2019 update 5.

**Comment by akukanov** [comment]
@mfdeakin, the problem is that you use `vector<bool>` which is not thread-safe. See e.g. https://en.cppreference.com/w/cpp/container/vector_bool: 

> `std::vector<bool>` behaves similarly to `std::vector`, but in order to be space efficient, it:
    ...
    - Does not guarantee that different elements in the same container can be modified concurrently by different threads.

**Comment by mfdeakin** [comment]
Ah, I didn't realize they had a thread unsafe specialization
