### ISSUE TITLE
Release brunch is missing files

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [intel/parallelstl#32]
If you open the release brunch, it does not have an algorithm header.
Since that is the default brunch, it's confusing

![Screenshot 2020-03-29 at 13 08 31](https://user-images.githubusercontent.com/11256077/77848689-6fb3ca00-71be-11ea-8afb-63d3b01b2d7f.png)

**Comment by DenisYaroshevskiy** [comment]
I mean - experimental has the algorithm header. But it doesn't seem to have algorithms

**Comment by AlexVeprev** [comment]
Hi @DenisYaroshevskiy,
You can find the `algorithm` header in `stdlib/pstl` directory: https://github.com/intel/parallelstl/tree/releases/stdlib/pstl

**Comment by DenisYaroshevskiy** [comment]
Thank you.

Any chance you can get the library on godbolt?

**Comment by AlexVeprev** [comment]
> Any chance you can get the library on godbolt?

It should be available with gcc-9.
From https://gcc.gnu.org/gcc-9/changes.html:

> **Runtime Library (libstdc++)**
> - Improved support for C++17, including:
>   - ...
>   - Parallel algorithms and <execution> (requires Thread Building Blocks 2018 or newer).
